# Generated by Django 2.2 on 2019-12-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('write_datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('write_datetime', models.DateTimeField(verbose_name='date published')),
                ('content', models.CharField(max_length=2048)),
                ('photo', models.CharField(max_length=512)),
                ('is_soldout', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TradeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_report_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.CharField(max_length=500)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Trade')),
                ('trade_report_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_report_user', to='market.User')),
                ('trade_write_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_write_user', to='market.User')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.User'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('write_datetime', models.DateTimeField(verbose_name='date published')),
                ('recv_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recv_user', to='market.User')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_user', to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_report_date', models.DateTimeField(verbose_name='date published')),
                ('content', models.CharField(max_length=500)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Comment')),
                ('comment_report_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_report_user', to='market.User')),
                ('comment_write_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_write_user', to='market.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Trade'),
        ),
        migrations.AddField(
            model_name='comment',
            name='write_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.User'),
        ),
    ]
