# Generated by Django 2.2 on 2019-12-22 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='write_datetime',
            new_name='pub_datetime',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='write_datetime',
            new_name='pub_datetime',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='write_datetime',
            new_name='pub_datetime',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='write_user',
        ),
        migrations.RemoveField(
            model_name='commentreport',
            name='comment_write_user',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='tradereport',
            name='trade_write_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_pub_user', to='market.User'),
        ),
        migrations.AddField(
            model_name='trade',
            name='interest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trade',
            name='pub_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_pub_user', to='market.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tradereport',
            name='write_report_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callee_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='callee_user', to='market.User')),
                ('caller_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caller_user', to='market.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_chat', to='market.Chat'),
        ),
    ]
